### ISSUE TITLE
--non-interactive flag runtime error

### ISSUE THREAD

**Issue by mjgaughan** [Halleck45/ast-metrics#57]
Howdy! 

When you run ast-metrics from the command line and specify the `--non-interactive` or `-i` flags for running static analysis, a runtime error is returned. 

Running: `ast-metrics a -i --report-markdown=report.md ../ConfirmEdit`

One gets:
```
AST Metrics is a language-agnostic static code analyzer.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1043b1290]

goroutine 12 [running]:
github.com/pterm/pterm.(*SpinnerPrinter).UpdateText(0x104ca79d0?, {0x140008d7890?, 0x140001d1f18?})
        /home/runner/go/pkg/mod/github.com/pterm/pterm@v0.12.79/spinner_printer.go:121 +0x20
github.com/halleck45/ast-metrics/src/Engine/Python.PythonRunner.DumpAST({0x0, 0x1400019a380, {{0x14000523340, 0x2, 0x2}, 0x14000a30780}})
        /home/runner/work/ast-metrics/ast-metrics/src/Engine/Python/PythonRunner.go:64 +0x158
github.com/halleck45/ast-metrics/src/Command.(*AnalyzeCommand).ExecuteRunnerAnalysis.func1()
        /home/runner/work/ast-metrics/ast-metrics/src/Command/AnalyzeCommand.go:290 +0x34
created by github.com/halleck45/ast-metrics/src/Command.(*AnalyzeCommand).ExecuteRunnerAnalysis in goroutine 1
        /home/runner/work/ast-metrics/ast-metrics/src/Command/AnalyzeCommand.go:289 +0x35c
```

**Comment by mjgaughan** [comment]
I'm unfamiliar with Go or how it allocates memory, so apologies if I'm not more help with this!

**Comment by Halleck45** [comment]
Thanks for the report! 

It will be fixed when https://github.com/Halleck45/ast-metrics/pull/58 will be merged.
